const tutors = [
  {
    id: "1",
    name: "Maryjo Delaguila",
    image2: "https://xsgames.co/randomusers/assets/avatars/female/21.jpg",
    rating: 5,
    courses: 4,
    expertise: "Computer Science",
    experience: "5 years of teaching experience",
    bio: "Passionate about sharing knowledge and helping students achieve their goals.",
    education: "Master's Degree in Computer Science",
    location: "New York, USA",
    contact: "+1 123-456-7890",
    email: "maryjo@example.com",
    availability: "Monday to Friday, 9am to 5pm",
  },
  {
    id: "2",
    name: "John Doe",
    image2: "https://xsgames.co/randomusers/assets/avatars/male/21.jpg",
    rating: 4,
    courses: 3,
    expertise: "Mathematics",
    experience: "3 years of tutoring experience",
    bio: "Dedicated to making math fun and understandable for all students.",
    education: "Bachelor's Degree in Mathematics",
    location: "Los Angeles, USA",
    contact: "+1 987-654-3210",
    email: "john@example.com",
    availability: "Weekends, 10am to 4pm",
  },
  {
    id: "3",
    name: "Fatos Kryeziu",
    image2: "https://media.licdn.com/dms/image/C4D03AQE2OdtrZmwLKA/profile-displayphoto-shrink_800_800/0/1657506748846?e=2147483647&v=beta&t=_ojUs-yH30nDdOM8FuM2DnzETHuIbB_76CA5_VxhYcI",
    rating: 4.5,
    courses: 4,
    expertise: "Physics",
    experience: "6 years of teaching experience",
    bio: "Specializes in making complex physics concepts easy to understand.",
    education: "PhD in Physics",
    location: "London, UK",
    contact: "+44 20 1234 5678",
    email: "fatos@example.com",
    availability: "Tuesday to Thursday, 2pm to 6pm",
  },
  {
    id: "4",
    name: "Adrola Dushi",
    image2: "https://ucreatestudio.com/wp-content/uploads/2013/02/female-CEO-headshot.jpg",
    rating: 4.8,
    courses: 6,
    expertise: "Business Management",
    experience: "8 years of industry experience",
    bio: "Helping aspiring entrepreneurs achieve success through practical guidance.",
    education: "MBA in Business Administration",
    location: "San Francisco, USA",
    contact: "+1 234-567-8901",
    email: "adrola@example.com",
    availability: "Monday to Friday, 9am to 7pm",
  },
  {
    id: "5",
    name: "Enver Gashi",
    image2: "https://media.licdn.com/dms/image/D5603AQFMV2hXARA-cg/profile-displayphoto-shrink_800_800/0/1691193350837?e=2147483647&v=beta&t=sUVUpRP7i29yLozKdEXrYSvluEAco-7yTN7NvMbUXMk",
    rating: 4.9,
    courses: 5,
    expertise: "Languages",
    experience: "10 years of language teaching experience",
    bio: "Passionate about fostering cultural understanding through language education.",
    education: "Bachelor's Degree in Linguistics",
    location: "Paris, France",
    contact: "+33 1 2345 6789",
    email: "enver@example.com",
    availability: "Monday to Friday, 8am to 4pm",
  },
  {
    id: "6",
    name: "Anela Berisha",
    image2: "https://headshots-inc.com/wp-content/uploads/2023/03/CEO-Headshot-Examples-3-1.jpg",
    rating: 4.5,
    courses: 5,
    expertise: "Art",
    experience: "Professional artist for 15 years",
    bio: "Inspiring creativity and imagination through art education.",
    education: "Bachelor's Degree in Fine Arts",
    location: "Berlin, Germany",
    contact: "+49 30 1234 5678",
    email: "anela@example.com",
    availability: "Weekends, 10am to 6pm",
  },
  {
    id: "7",
    name: "Hung Dowd",
    image2: "https://www.hcpc-uk.org/globalassets/image-library/about-us/people/bernie-ceo-profile-1.jpg",
    rating: 4.2,
    courses: 3,
    expertise: "Economics",
    experience: "Published author and lecturer",
    bio: "Making economics engaging and accessible for students of all levels.",
    education: "PhD in Economics",
    location: "Tokyo, Japan",
    contact: "+81 3 1234 5678",
    email: "hung@example.com",
    availability: "Monday to Wednesday, 10am to 3pm",
  },
  {
    id: "8",
    name: "Willian Hidy",
    image2: "https://i.pinimg.com/736x/07/33/ba/0733ba760b29378474dea0fdbcb97107.jpg",
    rating: 4.5,
    courses: 5,
    expertise: "Music",
    experience: "Professional musician and music teacher",
    bio: "Bringing the joy of music to students through personalized instruction.",
    education: "Bachelor's Degree in Music Education",
    location: "Sydney, Australia",
    contact: "+61 2 1234 5678",
    email: "willian@example.com",
    availability: "Weekdays, 9am to 5pm",
  },
  {
    id: "9",
    name: "Luana Santiano",
    image2: "https://headshots-inc.com/wp-content/uploads/2023/03/CEO-Headshot-Examples-2-1.jpg",
    rating: 4.7,
    courses: 6,
    expertise: "Science",
    experience: "PhD in Biology and research experience",
    bio: "Igniting curiosity and passion for science in young minds.",
    education: "PhD in Biology",
    location: "Toronto, Canada",
    contact: "+1 416 123 4567",
    email: "luana@example.com",
    availability: "Monday to Friday, 10am to 6pm",
  },
  {
    id: "10",
    name: "Beula Mohd",
    image2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGZBWqYsefx95NKSysIdEdkhEi0-d5QK9vX9VsijxsPSUhqXQkorPNV3qIa2RT0TNnu04&usqp=CAU",
    rating: 4.3,
    courses: 4,
    expertise: "Chemistry",
    experience: "Chemistry professor at a leading university",
    bio: "Making chemistry fascinating and understandable for students.",
    education: "PhD in Chemistry",
    location: "Singapore",
    contact: "+65 1234 5678",
    email: "beula@example.com",
    availability: "Weekends, 12pm to 6pm",
  },
];

export default tutors;

  
  